# Generated by Django 3.2.5 on 2021-07-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugin',
            old_name='module_name',
            new_name='module_filename',
        ),
    ]
