# Generated by Django 3.2.5 on 2021-07-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0002_rename_module_name_plugin_module_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plugin_type', models.CharField(max_length=50)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugin.plugin')),
            ],
        ),
    ]
