# Generated by Django 3.2.5 on 2021-09-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricedata', '0001_initial'),
        ('plugin', '0001_initial'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('pluginclass', models.ForeignKey(limit_choices_to={'plugin_type': 'FeatureImplementation'}, on_delete=django.db.models.deletion.CASCADE, to='plugin.pluginclass')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle_period', models.CharField(choices=[('1S', '1 Second'), ('5S', '5 Second'), ('10S', '10 Second'), ('15S', '15 Second'), ('30S', '30 Second'), ('1M', '1 Minute'), ('5M', '5 Minute'), ('10M', '10 Minute'), ('15M', '15 Minute'), ('30M', '30 Minute'), ('1H', '1 Hour'), ('3H', '3 Hour'), ('6H', '6 Hour'), ('12H', '12 Hour'), ('1D', '1 Day'), ('1W', '1 Week'), ('1MO', '1 Month')], max_length=3)),
                ('calculation_period', models.CharField(max_length=6)),
                ('active', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature.feature')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureExecutionDataSourceSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('datasource_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricedata.datasourcesymbol')),
                ('feature_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature.featureexecution')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('result', models.DecimalField(decimal_places=6, max_digits=12)),
                ('feature_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature.featureexecution')),
            ],
        ),
    ]
