# Generated by Django 3.2.5 on 2021-07-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('connection_params', models.CharField(max_length=500)),
                ('requirements_file', models.FileField(max_length=200, upload_to='pricedata\\datasources')),
                ('class_name', models.CharField(max_length=20)),
                ('module', models.FileField(max_length=200, upload_to='pricedata\\datasources')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieve_price_data', models.BooleanField(default=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricedata.datasource')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricedata.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('period', models.CharField(choices=[('1S', '1 Second'), ('5S', '5 Second'), ('10S', '10 Second'), ('15S', '15 Second'), ('30S', '30 Second'), ('1M', '1 Minute'), ('5M', '5 Minute'), ('10M', '10 Minute'), ('15M', '15 Minute'), ('30M', '30 Minute'), ('1H', '1 Hour'), ('3H', '3 Hour'), ('6H', '6 Hour'), ('12H', '12 Hour'), ('1D', '1 Day'), ('1W', '1 Week'), ('1M', '1 Month')], max_length=3)),
                ('bid_open', models.DecimalField(decimal_places=6, max_digits=12)),
                ('bid_high', models.DecimalField(decimal_places=6, max_digits=12)),
                ('bid_low', models.DecimalField(decimal_places=6, max_digits=12)),
                ('bid_close', models.DecimalField(decimal_places=6, max_digits=12)),
                ('ask_open', models.DecimalField(decimal_places=6, max_digits=12)),
                ('ask_high', models.DecimalField(decimal_places=6, max_digits=12)),
                ('ask_low', models.DecimalField(decimal_places=6, max_digits=12)),
                ('ask_close', models.DecimalField(decimal_places=6, max_digits=12)),
                ('volume', models.IntegerField()),
                ('datasource_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricedata.datasourcesymbol')),
            ],
        ),
    ]
